# 
# Home Assistant Automation Blueprint
#
# Synchronize on/off states on multiple devices with queue
#
# Revision 8 with single mode and delay
# Modified by Johan Schelin, Mar. 2021
# Modified from https://github.com/johanschelin/ha_blueprints/blob/4f1f05b6150257b3ad0b7f396010025ec110e26e/SyncStatesFour.yml

blueprint:
  name: Synchronize Three States
  description: Bind three entities together to act in unison (selected entites must all support the same state values)
  domain: automation
  input:
    switch_1:
      name: Entity 1
      selector:
        entity:
          #domain: switch          
    switch_2:
      name: Entity 2
      selector:
        entity:
          #domain: switch
    switch_3:
      name: Entity 3
      selector:
        entity:
          #domain: switch
mode: restart
max_exceeded: silent
variables:
  switch_1: !input 'switch_1'
  switch_2: !input 'switch_2'
  switch_3: !input 'switch_3'
trigger:
  - platform: state
    entity_id: !input 'switch_1'
  - platform: state
    entity_id: !input 'switch_2'
  - platform: state
    entity_id: !input 'switch_3'  
action:
- entity_id:
  - '{% if trigger.from_state.entity_id == switch_1 %} {{ switch_2 }}'
  - '{% if trigger.from_state.entity_id == switch_1 %} {{ switch_3 }}'
  - '{% if trigger.from_state.entity_id == switch_2 %} {{ switch_1 }}'
  - '{% if trigger.from_state.entity_id == switch_2 %} {{ switch_3 }}'
  - '{% if trigger.from_state.entity_id == switch_3 %} {{ switch_1 }}'
  - '{% if trigger.from_state.entity_id == switch_3 %} {{ switch_2 }}'
  service:  homeassistant.turn_{{ trigger.to_state.state }}
